apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app2
  template:
    metadata:
      labels:
        app: node-app2
    spec:
      containers:
      - name: node-app2
        image: <NODE_APP_IMAGE>
        ports:
          - containerPort: 8081
        env:
        - name: MONGODB_CONN_STRING
          value: <MONGODB_CONN_STRING>
        - name: APP_NAME
          value: APP2
---
apiVersion: v1
kind: Service
metadata:
  name: node-app2
spec:
  selector:
    app: node-app2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: node-app2
spec:
  rules:
  - http:
      paths:
      - path: /app2
        pathType: Prefix
        backend:
          serviceName: node-app2
          servicePort: 80