apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: node-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - path: "(.*)"
        pathType: Prefix
        backend:
          service:
            name: job-board-api
            port:
              number: 80