name: build-and-push-image-app1

on:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - 'config/**'
  #     - 'src/**'
  #     - 'Dockerfile'
  workflow_dispatch:

jobs:
  push-image:
    runs-on: ubuntu-latest

    steps:
      # Check out repository
      - uses: actions/checkout@v2

      # Build application
      - name: Build image
        run: docker build -t ${{ secrets.DIGITAL_OCEAN_REGISTRY }}/node-app:${{ github.sha }} . --build-arg APP_PORT=8080

      # Install Digital Ocean CLI
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITAL_OCEAN_TOKEN }}

      # Login to Digital Ocean
      - name: Log in to Digital Ocean
        run: doctl registry login

      # Push image to Digital Ocean registry
      - name: Push image to DigitalOcean Container Registry
        run: |
          docker push ${{ secrets.DIGITAL_OCEAN_REGISTRY }}/node-app:${{ github.sha }}

      - name: Update deployment file
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "<NODE_APP_IMAGE>"
          replace: "${{ secrets.DIGITAL_OCEAN_REGISTRY }}/node-app:${{ github.sha }}"
          include: "configs/app1-deployment.yaml"

      - name: Update ConnectionString
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "<MONGODB_CONN_STRING>"
          replace: "${{ secrets.MONGODB_CONN_STRING }}"
          include: "configs/app1-deployment.yaml"

      - name: Save DigitalOcean kubeconfig with short-lived credentials
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 xccelerate-dev

      - name: Deploy to DigitalOcean Kubernetes
        run: kubectl apply -f configs/app1-deployment.yaml

      - name: Verify deployment
        run: kubectl rollout status deployment/node-app