name: build-and-push-job-board

on:
  workflow_dispatch:

jobs:
  push-image:
    runs-on: ubuntu-latest

    steps:
      # Check out repository
      - uses: actions/checkout@v2

      # Login to AWS ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # Install Digital Ocean CLI
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITAL_OCEAN_TOKEN }}

      # Login to Digital Ocean
      - name: Log in to Digital Ocean
        run: doctl registry login

      - name: Save DigitalOcean kubeconfig with short-lived credentials
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 xccelerate-dev

      - name: Refresh cluster secret
        run: |
          kubectl delete secrets 406570422574.dkr.ecr.ap-southeast-1.amazonaws.com
          kubectl create secret docker-registry 406570422574.dkr.ecr.ap-southeast-1.amazonaws.com --docker-server=406570422574.dkr.ecr.ap-southeast-1.amazonaws.com --docker-username=AWS --docker-password=$PASS --docker-email=jason.m@xccelerate.co

      - name: Deploy to DigitalOcean Kubernetes
        run: kubectl apply -f configs/kube-job-board-deployment.yaml

      - name: Verify deployment
        run: kubectl rollout status deployment/job-board-api