name: build-and-push-image

on:
  workflow_dispatch:

jobs:
  push-image:
    runs-on: ubuntu-latest

    steps:
      # Check out repository
      - uses: actions/checkout@v2

      # Build application
      - name: Build image
        run: docker build . -t node-app

      # Install Digital Ocean CLI
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITAL_OCEAN_TOKEN }}

      # Login to Digital Ocean
      - name: Log in to Digital Ocean
        run: doctl registry login

      # Push image to Digital Ocean registry
      - name: Push image to DigitalOcean Container Registry
        run: |
          docker tag node-app ${{ secrets.DIGITAL_OCEAN_REGISTRY }}/node-app
          docker push ${{ secrets.DIGITAL_OCEAN_REGISTRY }}/node-app
